### ISSUE TITLE
Monorepo-ize

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/psdtools.github.io#1]
Keeping the Map and the Calculator is sync is getting annoying. Now that Tailwind's Oxide engine and LightningCSS integration is in alpha,[^1] there's no longer a major reason for us not to put everything in a single monorepo. This would involve using Bun's <https://bun.sh/docs/install/workspaces> feature, and properly configuring Turborepo.

[^1]: I hadn't wanted to keep them together if one would need PostCSS and the other wouldn't.
```[tasklist]
### Tasks
- [x] Merge in the packages folder (https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/)
- [x] Setup bun workspaces
- [x] Setup Turborepo
- [ ] Extract out common code
- [x] Re-add root files
- [x] Restart CI
```

**Comment by lishaduck** [comment]
Closing as completed, extracting code out into separate packages can be done as needed.
